### ISSUE TITLE
Log IDs of kicked/banned users

### ISSUE THREAD

**Issue by the-r3dacted** [TimWitzdam/discord_audit_log_export#1]
Currently this only logs the moderator's user ID. It would be helpful if it also logged the IDs of kicked/banned users as well. These can't change and will always point to the user, while they can just change their username.

**Comment by TimWitzdam** [comment]
That's true! I'll update the bot in a few days.

Thanks for the notice and hang tight for a notification here, when the update is released.

**Comment by TimWitzdam** [comment]
Fixed in commit [64af6d2](https://github.com/TimWitzdam/discord_audit_log_export/commit/64af6d22e8e710eb087a33036ff802f1451aa2b5)

**Comment by the-r3dacted** [comment]
Wow I was actually just going through my email and checked this post before deleting the first notification.

How long until it hits the bot?

**Comment by TimWitzdam** [comment]
Already updated

**Comment by the-r3dacted** [comment]
Well there seems to be a new issue today after the change. I'm trying to use it in two servers, and even with the default 1000, it just keeps thinking for ages until Discord says "The application did not respond"

**Comment by TimWitzdam** [comment]
Yea, try again now.

**Comment by the-r3dacted** [comment]
Thanks, it works now.
